language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

install:
  - npm install  # 安装hexo及插件

script:
  - hexo cl  # 清除
  - hexo g  # 生成

after_script:
  - cd public
  - git init
  - git config user.name "forecho"
  - git config user.email "caizhenghai@gmail.com"
  - git add .
  - git commit -m "Auto deploy from Travis-CI."
  - git push --force --quiet "https://$GH_Token@github.com/$GH_REPO.git" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - GH_REPO: 3li3/blog
    - secure: "W4BDVy9SyAAyu8wapaSPrceVWL9EAjdELcpb9RfqmrKrxWzG3eC5YmTglGzcJQQFSopNXbc4HVTZOzCUFqtX3M133/5vJGft/qafkXremBwO4OkIpye+CLolKbToxIWEulEj5W9tBe2EPD7Dzu0amuK41jxZRh+CzafkxA/Dg6uEs7mMcpZsi9ofeoBQZrUsMXC4zNKNAjhPpIJ/e8mSHp4bZXQnGvx/d5vqCrO/WvH4CwbwqnhBqPKkAGJHoP7YCbD5W2q4faq80WNrnhqMtvI//vV7Foyzx6riEIK5zrMZ/6z4/WI1dVMlZQhXmsAjdcRxnWvjjS5/uMw0KwaAQO7wkGiEpTxwig7RcGgoE4xPNc1hsSgTJAMBPZ8potRh417Zq10M6IlOY+kNOefPCZyx8S20O2uCdX0aPL/ldttGYOFzrpPkBUKzeqo9xq6jZoHMvnjAXAcU/pk4kxSNWfAU5erew/j+VCCZC6Ku17VJfxQ0Ro8+UWafoua4l8O0U6roFKcPq/ttNIumOgBHnl+y70uaXvFeuIxD1/ONo4OD3GAidWzi1on2H7eu6nmXbzl7/k6YxcZ8k5/d3AFBfaYU0yVOm1/AOEtT4j5Hx+K1DiUjJd5sDhr7WZiZPgETlCLxP2VaMoTwH5XW9QwX7nq/r7No86LNQlyWR6QJyw4="

notifications:
  email:
    - caizhenghai@gmail.com
  on_success: change
  on_failure: always
